// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qo1Pj8FsB1ks3neH-ZuQ3_1Wnn_hDTc',
    appId: '1:108863604729:web:e8730d1ef7a3758509df28',
    messagingSenderId: '108863604729',
    projectId: 'proker-24178',
    authDomain: 'proker-24178.firebaseapp.com',
    storageBucket: 'proker-24178.firebasestorage.app',
    measurementId: 'G-JVV1CSCGF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK07QdeLSXcSoFWfQk5mbkc7tY_fKzGiE',
    appId: '1:368168566691:android:4711143d79189a0c022416',
    messagingSenderId: '368168566691',
    projectId: 'e-study-6f999',
    databaseURL: 'https://e-study-6f999-default-rtdb.firebaseio.com',
    storageBucket: 'e-study-6f999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArYT0_ufme7Uzgg_hDcNTmk3bbqn5eg2c',
    appId: '1:368168566691:ios:b1a92a682f276682022416',
    messagingSenderId: '368168566691',
    projectId: 'e-study-6f999',
    databaseURL: 'https://e-study-6f999-default-rtdb.firebaseio.com',
    storageBucket: 'e-study-6f999.appspot.com',
    iosBundleId: 'com.proker',
  );
}
